[pytest]
addopts = -v -s --browser chromium --alluredir=allure-results
testpaths = tests
markers =
    qase: Qase TMS test case ID mapping
    api: Backend API test cases
    ui: Frontend Playwright UI test cases
