import os
from pathlib import Path

def generate_js20():
    cases = [{"title": "API Verification", "id": 81}, {"title": "UI Verification", "id": 57}]

    # Generate Backend API tests
    backend_code = [
        '"""',
        'Backend API Automated Test Suite for JS-20',
        'Generated by n8n QA Autotest Scaffolding Engine',
        '"""',
        'import pytest',
        'import allure',
        'from api.client import JuiceShopApiClient',
        '',
        '@allure.epic("OWASP Juice Shop")',
        '@allure.feature("JS-20: Authentication & Security")',
        '@allure.story("Backend REST API Validation")',
        'class TestJS20API:',
        '    """Автоматизированные проверки эндпоинтов и контрактов данных."""',
        ''
    ]

    for i, c in enumerate(cases):
        title = c.get('title', f"case_{i}")
        qid = c.get('id', 100+i)
        method_name = 'test_' + ''.join(e for e in title.lower().replace(' ', '_') if e.isalnum() or e == '_')[:40]
        if method_name.endswith('_'): method_name = method_name[:-1]
        
        backend_code.extend([
            f'    @allure.title("{title}")',
            f'    @pytest.mark.qase(id={qid})',
            f'    @pytest.mark.api',
            f'    def {method_name}(self, api_client: JuiceShopApiClient):',
            f'        """{title}"""',
            f'        with allure.step("1. Выполнение запроса к эндпоинту API"):',
            f'            response = api_client.get_connection_status()',
            f'            assert response is not None, "Служба Juice Shop должна быть доступна"',
            f'        with allure.step("2. Валидация схемы контракта и статуса ответа"):',
            f'            assert response.status_code in [200, 201, 400, 401], f"Неожиданный статус: {{response.status_code}}"',
            ''
        ])

    backend_path = Path("tests/backend/test_js20_api.py")
    backend_path.parent.mkdir(parents=True, exist_ok=True)
    backend_path.write_text('\n'.join(backend_code), encoding='utf-8')
    print(f"Created: {backend_path}")

    # Generate Frontend UI tests
    frontend_code = [
        '"""',
        'Frontend UI Automated Test Suite for JS-20',
        'Generated by n8n QA Autotest Scaffolding Engine (Playwright)',
        '"""',
        'import pytest',
        'import allure',
        'from playwright.sync_api import Page, expect',
        '',
        '@allure.epic("OWASP Juice Shop")',
        '@allure.feature("JS-20: Authentication & Security")',
        '@allure.story("Frontend Angular UI Validation")',
        'class TestJS20UI:',
        '    """Пользовательские сценарии интерфейса (Page Object Model)."""',
        ''
    ]

    for i, c in enumerate(cases[:2]):
        title = c.get('title', f"ui_case_{i}")
        qid = c.get('id', 200+i)
        method_name = 'test_' + ''.join(e for e in title.lower().replace(' ', '_') if e.isalnum() or e == '_')[:40]
        if method_name.endswith('_'): method_name = method_name[:-1]
        
        frontend_code.extend([
            f'    @allure.title("{title}")',
            f'    @pytest.mark.qase(id={qid})',
            f'    @pytest.mark.ui',
            f'    def {method_name}(self, page: Page):',
            f'        """{title}"""',
            f'        with allure.step("1. Открытие целевой страницы приложения"):',
            f'            page.goto("http://localhost:3000/#/")',
            f'        with allure.step("2. Проверка отображения ключевых элементов интерфейса"):',
            f'            expect(page).to_have_title(/OWASP Juice Shop/)',
            ''
        ])

    frontend_path = Path("tests/frontend/test_js20_ui.py")
    frontend_path.parent.mkdir(parents=True, exist_ok=True)
    frontend_path.write_text('\n'.join(frontend_code), encoding='utf-8')
    print(f"Created: {frontend_path}")

if __name__ == "__main__":
    generate_js20()
