// n8n Code node: "Создание файлов автотестов на Python"
// Подготовка файлов автотестов на основе утвержденных тест-кейсов

const filterData = $('Фильтр: Задача взята в работу').first().json
const prevCases = $('Создание тест-кейсов без повторов').first().json
const issue = $('Jira: Загрузить данные задачи').first().json

const issueKey = filterData.issueKey || 'JS-16'
const issueSummary = issue.fields?.summary || 'User Profile & Authentication'
const keyLower = issueKey.toLowerCase().replace(/[^a-z0-9]/g, '')

const cases = prevCases.cases || []
const toAutomate = cases.filter(c => c.automation === 1 || c.type === 'automated' || !c.title.includes('Manual'))

// Разделение по уровням пирамиды
const backendCases = toAutomate.filter(c => c.layer === 'api' || c.suite?.toLowerCase().includes('backend') || c.title.toLowerCase().includes('api') || c.title.toLowerCase().includes('jwt') || c.title.toLowerCase().includes('регистрация'))
const frontendCases = toAutomate.filter(c => !backendCases.includes(c))

// Генерация шаблона Backend API теста
const backendFileName = `test_${keyLower}_api.py`
const backendCode = [
  '"""',
  `Backend API Automated Test Suite for ${issueKey}: ${issueSummary}`,
  'Generated by n8n QA Autotest Scaffolding Engine',
  '"""',
  'import pytest',
  'import allure',
  'from api.client import JuiceShopApiClient',
  'from schemas.models import UserRegistrationResponse, LoginResponse, ApiErrorResponse',
  '',
  `@allure.epic("OWASP Juice Shop")`,
  `@allure.feature("${issueKey}: ${issueSummary}")`,
  `@allure.story("Backend REST API Validation")`,
  `class Test${keyLower.toUpperCase()}API:`,
  '    """Автоматизированные проверки эндпоинтов и контрактов данных."""',
  ''
]

for (const c of (backendCases.length ? backendCases : cases.slice(0, 3))) {
  const qaseId = c.qaseId || c.id || 81
  const methodName = 'test_' + (c.title || 'case').toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 40)
  backendCode.push(`    @allure.title("${c.title || 'API Verification'}")`)
  backendCode.push(`    @pytest.mark.qase(id=${qaseId})`)
  backendCode.push(`    @pytest.mark.api`)
  backendCode.push(`    def ${methodName}(self, api_client: JuiceShopApiClient):`)
  backendCode.push(`        """${c.title}"""`)
  backendCode.push(`        with allure.step("1. Выполнение запроса к эндпоинту API"):`)
  backendCode.push(`            response = api_client.get_connection_status()`)
  backendCode.push(`            assert response is not None, "Служба Juice Shop должна быть доступна"`)
  backendCode.push(`        with allure.step("2. Валидация схемы контракта и статуса ответа"):`)
  backendCode.push(`            assert response.status_code in [200, 201, 400, 401], f"Неожиданный статус: {response.status_code}"`)
  backendCode.push('')
}

// Генерация шаблона Frontend UI теста
const frontendFileName = `test_${keyLower}_ui.py`
const frontendCode = [
  '"""',
  `Frontend UI Automated Test Suite for ${issueKey}: ${issueSummary}`,
  'Generated by n8n QA Autotest Scaffolding Engine (Playwright)',
  '"""',
  'import pytest',
  'import allure',
  'from playwright.sync_api import Page, expect',
  'from pages.login_page import LoginPage',
  'from pages.register_page import RegisterPage',
  '',
  `@allure.epic("OWASP Juice Shop")`,
  `@allure.feature("${issueKey}: ${issueSummary}")`,
  `@allure.story("Frontend Angular UI Validation")`,
  `class Test${keyLower.toUpperCase()}UI:`,
  '    """Пользовательские сценарии интерфейса (Page Object Model)."""',
  ''
]

for (const c of (frontendCases.length ? frontendCases : cases.slice(0, 2))) {
  const qaseId = c.qaseId || c.id || 57
  const methodName = 'test_' + (c.title || 'ui_case').toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 40)
  frontendCode.push(`    @allure.title("${c.title || 'UI Verification'}")`)
  frontendCode.push(`    @pytest.mark.qase(id=${qaseId})`)
  frontendCode.push(`    @pytest.mark.ui`)
  frontendCode.push(`    def ${methodName}(self, page: Page):`)
  frontendCode.push(`        """${c.title}"""`)
  frontendCode.push(`        with allure.step("1. Открытие целевой страницы приложения"):`)
  frontendCode.push(`            page.goto("http://localhost:3000/#/")`)
  frontendCode.push(`        with allure.step("2. Проверка отображения ключевых элементов интерфейса"):`)
  frontendCode.push(`            expect(page).to_have_title(/OWASP Juice Shop/)`)
  frontendCode.push('')
}

const kind = prevCases.kind || filterData.kind || 'generic'
const isBackendOnly = kind === 'backend'
const isFrontendOnly = kind === 'frontend'

const files = []
if (!isFrontendOnly) {
  files.push({
    type: 'backend',
    fileName: backendFileName,
    stagingPath: `tests/review/backend/${backendFileName}`,
    targetPath: `tests/backend/${backendFileName}`,
    testCount: backendCases.length || 1,
    code: backendCode.join('\n')
  })
}
if (!isBackendOnly) {
  files.push({
    type: 'frontend',
    fileName: frontendFileName,
    stagingPath: `tests/review/frontend/${frontendFileName}`,
    targetPath: `tests/frontend/${frontendFileName}`,
    testCount: frontendCases.length || 1,
    code: frontendCode.join('\n')
  })
}

return [{
  json: {
    issueKey,
    issueSummary,
    kind,
    scaffoldTimestamp: new Date().toISOString(),
    files
  }
}]
